# Generated by Django 5.2.1 on 2025-07-08 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clave_secreta', models.CharField(blank=True, max_length=128, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16, unique=True)),
                ('fecha_vencimiento', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='cuentas.cuentabancaria')),
            ],
        ),
    ]
