# Generated by Django 5.2.1 on 2025-05-20 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16, unique=True)),
                ('fecha_vencimiento', models.DateField()),
                ('ccv', models.CharField(max_length=3)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='cuentas.cuentabancaria')),
            ],
        ),
    ]
