# Generated by Django 5.2.1 on 2025-06-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_tarjetabancaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjetabancaria',
            old_name='ccv',
            new_name='cvv',
        ),
    ]
