# Generated by Django 5.2.1 on 2025-06-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_rename_ccv_tarjetabancaria_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='clave_secreta',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
