# Generated by Django 5.2.1 on 2025-06-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_imagencarrusel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenCarrusel',
        ),
    ]
