# Generated by Django 5.2.1 on 2025-06-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_historialiniciosesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='solicitudprestamo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='HistorialInicioSesion',
        ),
        migrations.DeleteModel(
            name='SolicitudPrestamo',
        ),
    ]
